MLhelp/MLhelp/urls.py
from django.contrib import admin
from django.urls import path,include
import authentication.views 
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #AUTH
    path('admin/', admin.site.urls),
    path('signup/', authentication.views.signup_page, name='signup'),
    path('login/', LoginView.as_view(
            template_name='authentication/login.html',
            redirect_authenticated_user=True),
        name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),


    #Dashboard
    path('', include('dashboard.urls', namespace='dashboard')),


    #dataset
    path('', include('datasets.urls', namespace='datasets')),

    #graphics
    #path('', include('graphics.urls', namespace='graphics')),
    #mlapp
    path('', include('mlapp.urls', namespace='mlapp')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MLhelp/dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.home, name='home'),
    path('workspace',views.home, name='home'),
    path('workspace/create/', views.create_workspace, name='create_workspace'),
    path('workspace/<int:workspace_id>/', views.detail_workspace, name='detail_workspace'),
    path('workspace/<int:workspace_id>/update/', views.update_workspace, name='update_workspace'),
    path('workspace/<int:workspace_id>/delete/', views.delete_workspace, name='delete_workspace'),
    path('workspace/<int:workspace_id>/datasets/', include('datasets.urls', namespace='datasets')),
]

MLhelp/datasets/urls.py
# dataset/urls.py
from django.urls import path
from . import views

app_name = 'datasets'  # Ceci définit le namespace

urlpatterns = [
    path('workspace/<int:workspace_id>/datasets/create/', views.create_dataset, name='create_dataset'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/', views.detail_dataset, name='detail_dataset'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/update-cell/', views.update_cell, name='update_cell'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/delete-rows/', views.delete_rows, name='delete_rows'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/save/', views.save_dataset, name='save_dataset'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/update/', views.update_dataset, name='update_dataset'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/delete/', views.delete_dataset, name='delete_dataset'),

]

MLhelp/mlapp/urls.py
# dataset/urls.py
from django.urls import path
from . import views

app_name = 'mlapp'  # Ceci définit le namespace

urlpatterns = [
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/model/choose-model/', views.choose_model_way, name='choose_model_way'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/model/get-get-pre-model/', views.get_pre_model, name='get_pre_model'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/model/get-custom-model/', views.get_custom_model, name='get_custom_model'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/model/detail/', views.detail_model, name='detail_model'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/model/<int:model_id>/delete/', views.delete_model, name='delete_model'),
    path('workspace/<int:workspace_id>/datasets/<int:dataset_id>/model/<int:model_id>/detail/', views.model_manip, name='model_manip'),
]

MLhelp/dashboard/models.py
from django.db import models
from django.conf import settings
# Create your models here.

@staticmethod
def is_workspace_table_empty():
    return not Workspace.objects.exists()


class Workspace(models.Model):
    owner        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name         = models.CharField(max_length=255)
    description  = models.TextField(blank=True, null=True)
    created_at   = models.DateTimeField(auto_now_add=True)

MLhelp/dashboard/forms.py
from django import forms
from .models import Workspace

class WorkspaceForm(forms.ModelForm):
    class Meta:
        model  = Workspace
        fields = ['name', 'description'] 

MLhelp/dashboard/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required  
from .models import Workspace
from datasets.models import Datasets
from .forms import WorkspaceForm
import pandas as pd
import json
from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

#WORKPLACE
@login_required
def create_workspace(request):
    if request.method == 'POST':
        form = WorkspaceForm(request.POST)
        if form.is_valid():
            workspace       = form.save(commit=False)  # Ne pas encore sauvegarder dans la base de données
            workspace.owner = request.user           # Associer l'utilisateur connecté comme propriétaire
            workspace.save()                         # Maintenant, sauvegarder dans la base de données
            return redirect('dashboard:detail_workspace', workspace_id=workspace.id)                # Rediriger après le succès
        
    else:
        form = WorkspaceForm()
    return render(request, 'dashboard/create_workspace.html', {'form': form})

@login_required
def home(request):
    print("ok")
    workspaces = Workspace.objects.filter(owner=request.user)
    return render(request, 'dashboard/home.html',
                    {'workspaces' : workspaces}
                    )

@login_required
def detail_workspace(request, workspace_id):
    # Get the Workspace instance based on the workspace_id from the URL
    workspace = get_object_or_404(Workspace, id=workspace_id)
    
    # Filter datasets based on the retrieved workspace
    datasets = Datasets.objects.filter(workspace=workspace)
    
    # Render the template and pass the datasets to the context
    return render(request, 'dashboard/detail_workspace.html', {'datasets': datasets,'workspace': workspace})

@login_required
def update_workspace(request,workspace_id):
    workspace = get_object_or_404(Workspace, id=workspace_id, owner=request.user)
    if request.method == 'POST':
        form = WorkspaceForm(request.POST, instance=workspace)
        if form.is_valid():
            form.save()
            return redirect('dashboard:detail_workspace', workspace_id=workspace_id)
    else:
        form = WorkspaceForm(instance=workspace)
    return render(request, 'dashboard/update_workspace.html', {'form': form})


@login_required
def delete_workspace(request, workspace_id):
    workspace = get_object_or_404(Workspace, id=workspace_id, owner=request.user)
    if request.method == 'POST':
        workspace.delete()
        return redirect('dashboard:home')
    return render(request, 'dashboard/delete_workspace.html', {'workspace': workspace})

MLhelp/dashboard/templates/dashboard/create_workspace.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Workspace</title>
</head>
<body>
    <h1>Create a New Workspace</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Workspace</button>
    </form>

    <a href="{% url 'dashboard:home' %}">Back to Home</a>
</body>
</html>

MLhelp/dashboard/templates/dashboard/delete_workspace.html
{% extends 'base.html' %}
{% block content %}
  <h2>Supprimer {{ workspace.name }}</h2>
  <p>Êtes-vous sûr de vouloir supprimer ?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Oui, supprimer</button>
  </form>
  <a href="{% url 'dashboard:home' %}">Annuler</a>
{% endblock %}

MLhelp/dashboard/templates/dashboard/detail_workspace.html
{% extends 'base.html' %}
{% block content %}
    <p>Vous êtes connecté !</p>
    <p>{{ workspace.name }}</p>
    <ul>
        {% for dataset in datasets %}
          <li>
            <a href="{% url 'datasets:detail_dataset' workspace.id dataset.id %}">{{ dataset.name }}</a>
            - <a href="{% url 'datasets:update_dataset' workspace.id dataset.id %}">[modifier]</a>
            - <a href="{% url 'datasets:delete_dataset' workspace.id dataset.id %}">[supprimer]</a>
          </li>
        {% endfor %}
      </ul>
      <p><a href="{% url 'datasets:create_dataset' workspace.id %}">ajouter un dataset</a></p>
{% endblock content %}
</body>
</html>

MLhelp/dashboard/templates/dashboard/home.html
{% extends 'base.html' %}
{% block content %}
    <p>Vous êtes connecté !</p>
    <p>Vos projets !</p>
    <ul>
        {% for workspace in workspaces %}
          <li>
            <a href="{% url 'dashboard:detail_workspace' workspace.id %}">{{ workspace.name }}</a>
            - <a href="{% url 'dashboard:update_workspace' workspace.id %}">[modifier]</a>
            - <a href="{% url 'dashboard:delete_workspace' workspace.id %}">[supprimer]</a>
          </li>
        {% endfor %}
      </ul>
      <p><a href="{% url 'dashboard:create_workspace' %}">créer un projet</a></p>
{% endblock content %}
</body>
</html>

MLhelp/dashboard/templates/dashboard/update_workspace.html
{% block content %}
  <h2>Modifier le workspace</h2>
  <form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">Mettre à jour</button>
  </form>
{% endblock %}